# Generated by Django 5.2.4 on 2025-11-02 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClassIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_number', models.CharField(max_length=50, verbose_name='Номер МК')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('cover', models.ImageField(upload_to='mk_covers/', verbose_name='Обложка (500x300)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание МК (HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
            ],
            options={
                'verbose_name': 'Идея для МК',
                'verbose_name_plural': 'Идеи для МК',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelsIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reels_number', models.CharField(max_length=50, verbose_name='Номер Reels')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('plot_description', models.TextField(verbose_name='Описание сюжета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
            ],
            options={
                'verbose_name': 'Идея для Reels',
                'verbose_name_plural': 'Идеи для Reels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата постановки (текст)')),
                ('deadline_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дедлайн (текст)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('has_question', models.BooleanField(default=False, verbose_name='Есть вопрос')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочная')),
                ('is_planned', models.BooleanField(default=False, verbose_name='Плановая')),
                ('is_think', models.BooleanField(default=False, verbose_name='Подумать')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыть задачу (только админ видит)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterClassFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='mk_files/', verbose_name='Файл')),
                ('mk_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='idea.masterclassidea')),
            ],
            options={
                'verbose_name': 'Файл МК',
                'verbose_name_plural': 'Файлы МК',
            },
        ),
        migrations.CreateModel(
            name='MasterClassExampleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('mk_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_links', to='idea.masterclassidea')),
            ],
            options={
                'verbose_name': 'Ссылка на пример МК',
                'verbose_name_plural': 'Ссылки на примеры МК',
            },
        ),
        migrations.CreateModel(
            name='MasterClassDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_text', models.CharField(max_length=255, verbose_name='Дата проведения (текст)')),
                ('mk_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='idea.masterclassidea')),
            ],
            options={
                'verbose_name': 'Дата МК',
                'verbose_name_plural': 'Даты МК',
            },
        ),
        migrations.CreateModel(
            name='MasterClassMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('source_link', models.URLField(blank=True, null=True, verbose_name='Где взять (ссылка)')),
                ('received_date_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата получения материалов')),
                ('cost_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стоимость')),
                ('mk_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='idea.masterclassidea')),
            ],
            options={
                'verbose_name': 'Материал для МК',
                'verbose_name_plural': 'Материалы для МК',
            },
        ),
        migrations.CreateModel(
            name='ReelsExampleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('reels_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_links', to='idea.reelsidea')),
            ],
            options={
                'verbose_name': 'Ссылка на пример Reels',
                'verbose_name_plural': 'Ссылки на примеры Reels',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='task_files/', verbose_name='Файл')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='idea.task')),
            ],
            options={
                'verbose_name': 'Прикрепление',
                'verbose_name_plural': 'Прикрепления',
            },
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пометки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='idea.task')),
            ],
            options={
                'verbose_name': 'Пометка',
                'verbose_name_plural': 'Пометки',
                'ordering': ['-created_at'],
            },
        ),
    ]
