# Generated by Django 5.2.4 on 2025-11-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_masterclassidea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclassexamplelink',
            name='link',
            field=models.TextField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='masterclassmaterial',
            name='source_link',
            field=models.TextField(blank=True, null=True, verbose_name='Где взять (ссылка)'),
        ),
        migrations.AlterField(
            model_name='reelsexamplelink',
            name='link',
            field=models.TextField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
