# Generated by Django 5.2.4 on 2025-11-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_reelsidea_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelsidea',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
