# Generated by Django 5.2.4 on 2025-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_alter_reelsidea_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelsidea',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Одобрено'),
        ),
        migrations.AlterField(
            model_name='reelsidea',
            name='plot_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сюжета'),
        ),
        migrations.AlterField(
            model_name='reelsidea',
            name='reels_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер Reels'),
        ),
        migrations.AlterField(
            model_name='reelsidea',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
