# Generated by Django 5.2.4 on 2025-11-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_alter_reelsidea_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclassidea',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='mk_covers/', verbose_name='Обложка (500x300)'),
        ),
        migrations.AlterField(
            model_name='masterclassidea',
            name='mk_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер МК'),
        ),
        migrations.AlterField(
            model_name='masterclassidea',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
