# Generated by Django 5.2.4 on 2025-12-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0007_alter_masterclassidea_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClassTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Тег МК',
                'verbose_name_plural': 'Теги МК',
            },
        ),
        migrations.CreateModel(
            name='ReelsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Тег рилсов',
                'verbose_name_plural': 'Теги рилсов',
            },
        ),
        migrations.AddField(
            model_name='masterclassidea',
            name='tags',
            field=models.ManyToManyField(blank=True, to='idea.masterclasstag'),
        ),
        migrations.AddField(
            model_name='reelsidea',
            name='tags',
            field=models.ManyToManyField(blank=True, to='idea.reelstag'),
        ),
    ]
