# Generated by Django 5.2.4 on 2026-02-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_masterclasstag_reelstag_masterclassidea_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelsFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Фильтр Reels',
                'verbose_name_plural': 'Фильтры Reels',
            },
        ),
        migrations.AddField(
            model_name='reelsidea',
            name='is_bad',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Забраковано'),
        ),
        migrations.AddField(
            model_name='reelsidea',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отснято'),
        ),
        migrations.AddField(
            model_name='reelsidea',
            name='filters',
            field=models.ManyToManyField(blank=True, to='idea.reelsfilter'),
        ),
    ]
