# Generated by Django 5.2.4 on 2026-02-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_reelsfilter_reelsidea_is_bad_reelsidea_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelsidea',
            name='is_bad',
            field=models.BooleanField(blank=True, default=False, verbose_name='Забраковано'),
        ),
        migrations.AlterField(
            model_name='reelsidea',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, verbose_name='Отснято'),
        ),
    ]
