# Generated by Django 5.2.4 on 2025-07-31 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.lessonstatus'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.lessontype'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.paymentstatus'),
        ),
    ]
