# Generated by Django 5.2.4 on 2025-08-19 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_notestatus_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data.paymentstatus'),
        ),
    ]
