# Generated by Django 5.2.4 on 2025-08-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_lesson_payment_status'),
        ('user', '0005_alter_pupil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pupils',
            field=models.ManyToManyField(related_name='lessons', to='user.pupil', verbose_name='Ученики'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pupils_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
