# Generated by Django 5.2.4 on 2025-08-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_note_created_at_note_text1_note_text2_note_text3'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='comment_hidden',
            field=models.TextField(blank=True, null=True),
        ),
    ]
