# Generated by Django 5.2.4 on 2025-08-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_lesson_comment_hidden'),
        ('user', '0005_alter_pupil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pupils',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='user.pupil', verbose_name='Ученики'),
        ),
    ]
