# Generated by Django 5.2.4 on 2025-08-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Почта')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pupils',
            field=models.ManyToManyField(blank=True, to='user.pupil', verbose_name='Ученики'),
        ),
    ]
