# Generated by Django 5.2.4 on 2025-08-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_pupil_user_pupils'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': '2. Ученики'},
        ),
    ]
