# Generated by Django 5.2.4 on 2025-11-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_pupil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_support',
            field=models.BooleanField(default=False, verbose_name='Саппорт'),
        ),
    ]
