# Generated by Django 5.2.4 on 2026-01-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
